### PR TITLE
Fix clippy

### LINKED ISSUE #259: Clippy lints
Currently clippy generates a ton of lints, even though we have clippy in CI.

Is there a reason for that? I am happy to write a PR that resolves the lints.

### PR DESCRIPTION
**Pull request by uncomputable**
Progress towards #259. There are still many warnings outside of `bitvm/bitvm`.

There were a lot of clippy lints. Especially when running `cargo clippy --all-targets`. This PR resolves all of them.

I tried to be as conservative as possible, keeping the general function structure the same, not deleting any types, etc. At some places, I allowed the lint instead of resolving it. These lines are searchable via `git grep` and can be fixed in follow-up PRs.

The [manual_div_ceil lint explanation](https://rust-lang.github.io/rust-clippy/master/index.html#manual_div_ceil) might help reviewers.

There is also the usage of `cfg_chunks_mut!` from `ark_std` that caused problems due to the missing `parallel` feature. I replaced that line with [the non-parallel function call, as by the macro](https://github.com/arkworks-rs/std/blob/b0cbdeb097b42f61880b3bee19e8dd37258d23a5/src/lib.rs#L179-L192).

```
warning: unexpected `cfg` condition value: `parallel`
   --> bitvm/src/bn254/ell_coeffs.rs:329:21
    |
329 |         let mut f = cfg_chunks_mut!(pairs, 4)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: expected values for `feature` are: `fuzzing`
    = note: using a cfg inside a macro will use the cfgs from the destination crate and not the ones from the defining crate
    = help: try referring to `cfg_chunks_mut` crate for guidance on how handle this unexpected cfg
    = help: the macro `cfg_chunks_mut` may come from an old version of the `ark_std` crate, try updating your dependency with `cargo update -p ark_std`
    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
    = note: `#[warn(unexpected_cfgs)]` on by default
    = note: this warning originates in the macro `cfg_chunks_mut` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### CODE REVIEW

**Review by AaronFeickert — APPROVED** [review]
LGTM, pending a rebase since #257 has been merged.

**Review by manishbista28 — APPROVED** [review]

**Comment by manishbista28** [comment]
looks good to me

File: bitvm/src/bn254/ell_coeffs.rs [hunk 1]
```diff
@@ -28,13 +27,15 @@ pub struct G2Prepared {
 pub type EllCoeff = (ark_bn254::Fq2, ark_bn254::Fq2, ark_bn254::Fq2);
 
 #[derive(Clone, Copy, Debug)]
+#[allow(dead_code)]
```
Comment (manishbista28) [inline bitvm/src/bn254/ell_coeffs.rs:30]: can remove G2HomProjective if it's in the scope of this PR

File: bitvm/src/chunk/g16_runner_core.rs [hunk 2]
```diff
@@ -326,10 +326,10 @@ pub(crate) fn groth16_generate_segments(
...
 
     // (t2, t3) = (le.t2, le.t3);
-    let tmp_q2f = frob_q_power(pubs.q2, -1);
-    t2 = (t2 + tmp_q2f).into_affine();
-    let tmp_q3f = frob_q_power(pubs.q3, -1);
-    t3 = (t3 + tmp_q3f).into_affine();
+    // let tmp_q2f = frob_q_power(pubs.q2, -1);
+    // t2 = (t2 + tmp_q2f).into_affine();
+    // let tmp_q3f = frob_q_power(pubs.q3, -1);
+    // t3 = (t3 + tmp_q3f).into_affine();
```
Comment (manishbista28) [inline bitvm/src/chunk/g16_runner_core.rs:332]: can delete these comments too, but i'm okay either way.

Comment (AaronFeickert) [reply bitvm/src/chunk/g16_runner_core.rs:332]: Thanks @manishbista28 for checking this. I recommend deleting instead of commenting. We have them in the repository history if needed.

Comment (AaronFeickert) [reply bitvm/src/chunk/g16_runner_core.rs:332]: Same with lines 1058-1062 in the same file?

Comment (manishbista28) [reply bitvm/src/chunk/g16_runner_core.rs:332]: yes, same for comments in lines 1058-1062.

**Comment by AaronFeickert** [comment]
We should update CI to fail on linter warnings (and enforce passing CI for merges).

**Comment by uncomputable** [comment]
I removed the unused code and updated CI to deny clippy warnings.

**Comment by AaronFeickert** [comment]
Many more lints from bridge.

**Comment by uncomputable** [comment]
I reverted the CI change because clippy finds a lot of warnings in the bridge and in other places. Fixing these warnings is out of scope for this PR.

**Review by AaronFeickert — APPROVED** [review]
LGTM, pending CI.

**Review by AaronFeickert — APPROVED** [review]

**Comment by uncomputable** [comment]
Rebased onto `main`
